version: 2

jobs:
  build:
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run: go fmt
      - run: go build
      - run: go test

  integration_testnet:
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run:
          name: "Launch proxy"
          background: true
          command: |
            export LOTUS_RPC_URL=${LOTUS_RPC_URL_TESTNET}
            export LOTUS_RPC_TOKEN=${LOTUS_RPC_TOKEN_TESTNET}
            go run main.go
      - run:
          name: "Run tests"
          background: true
          command: |
            echo "TODO: Run rosetta-cli?"

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - integration_testnet