version: 2

jobs:
  build:
    docker:
      - image: golang:1.14
    working_directory: /rosetta-filecoin-lib
    steps:
      - checkout
      - run: make build
      - run: go test ./rosetta/services

  checks:
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      - run:
          name: "check go mod tidy"
          command: |
            go mod tidy
            git diff --exit-code -- go.mod go.sum
      - run: golangci-lint --version
      - run: golangci-lint run -E gofmt -E gosec -E goconst -E gocritic
  #      - run: golangci-lint run -E gofmt -E gosec -E goconst -E godox -E gocritic

  integration_testnet:
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run:
          name: "Prebuild"
          command: |
            make build
      - run:
          name: "Launch proxy"
          background: true
          command: |
            export LOTUS_RPC_URL=${LOTUS_RPC_URL_TESTNET}
            export LOTUS_RPC_TOKEN=${LOTUS_RPC_TOKEN_TESTNET}
            ./rosetta-filecoin-proxy
      - run:
          name: "Give time for the proxy to start"
          command: sleep 3
      - run:
          name: "Run tests"
          command: |
            go test ./rosetta/tests

  integration_rosetta_cli:
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run:
          name: "Prebuild"
          command: |
            make build
      - run:
          name: "Launch proxy"
          background: true
          command: |
            export LOTUS_RPC_URL=${LOTUS_RPC_URL_TESTNET}
            export LOTUS_RPC_TOKEN=${LOTUS_RPC_TOKEN_TESTNET}
            ./rosetta-filecoin-proxy
      - run:
          name: "Give time for the proxy to start"
          command: sleep 3
      - run:
          name: "Run rosetta-cli tests"
          command: |
            cd rosetta/tests
            ./rosetta_cli_test.sh

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - checks
      - integration_testnet
      - integration_rosetta_cli