version: 2.1

commands:
  ffi_deps:
    steps:
      - run: apt update && apt install -yy mesa-opencl-icd jq hwloc libhwloc-dev
      - run: ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so
      - run: git submodule update --init --recursive

jobs:
  build:
    docker:
      - image: golang:1.15
    working_directory: /rosetta-filecoin-lib
    steps:
      - checkout
      - ffi_deps
      - run: make build
      - run: make test

  checks:
    docker:
      - image: golang:1.15
    steps:
      - checkout
      - ffi_deps
      - run: make install_lint
      - run: make build_CI
      - run: make check-modtidy
      - run: make lint

  integration_testnet:
    docker:
      - image: golang:1.15
    steps:
      - checkout
      - ffi_deps
      - run:
          name: "Prebuild"
          command: |
            make build_CI
      - run:
          name: "Launch proxy"
          background: true
          command: |
            export LOTUS_RPC_URL=${LOTUS_RPC_URL_TESTNET}
            export LOTUS_RPC_TOKEN=${LOTUS_RPC_TOKEN_TESTNET}
            ./rosetta-filecoin-proxy
      - run:
          name: "Give time for the proxy to start"
          command: sleep 3
      - run:
          name: "Run tests"
          command: |
            make test_integration

workflows:
  version: 2
  build_all:
    jobs:
      - build
      - checks
      - integration_testnet
