version: 2

jobs:
  build:
    docker:
      - image: golang:1.14
    working_directory: /rosetta-filecoin-lib
    steps:
      - checkout
      - run: go fmt
      - run: go build
      - run: go test
workflows:
  version: 2
  build_all:
    jobs:
      - build
