name: rosetta-cli

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: zondax-runners
    container:
      image: golang:1.20
      options: --tty
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Temporary Global Git Configuration
        run: |
          git config --global --add safe.directory /__w/rosetta-filecoin-proxy/rosetta-filecoin-proxy

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Install dependencies
        run: apt update && apt install -yy build-essential bzr jq pkg-config mesa-opencl-icd ocl-icd-opencl-dev hwloc libhwloc-dev net-tools
      - name: Test
        run: make test

  rosetta_cli:
    name: Rosetta CLI integration tests
    runs-on: zondax-runners
    container:
      image: golang:1.20
      options: --tty
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        include:
#          - network: mainnet
#            url: LOTUS_MAINNET_RPC_URL
#          - network: devnet
#            url: LOTUS_DEVNET_RPC_URL
          - network: calibration
            url: LOTUS_CALIBRATION_RPC_URL
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20' # The Go version to download (if necessary) and use.

      - name: Temporary Global Git Configuration
        run: |
          git config --global --add safe.directory /__w/rosetta-filecoin-proxy/rosetta-filecoin-proxy

      - run: git submodule update --init --recursive
      - run: apt update && apt install -yy build-essential bzr jq pkg-config mesa-opencl-icd ocl-icd-opencl-dev hwloc libhwloc-dev net-tools
      - run: make build_CI
      - name: Run proxy in background
        run: ./rosetta-filecoin-proxy&
        env:
          LOTUS_RPC_URL: ${{ secrets[matrix.url] }}
      - name: Sleep for 3 seconds
        run: sleep 3

##Debug
      - name: Check open ports
        run: netstat -tuln

      - run: ./rosetta_cli_test_PR.sh ${{ matrix.network }}
        working-directory: ./rosetta/tests
