name: rosetta-cli

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  rosetta_cli:
    runs-on: self-hosted
    timeout-minutes: 5760
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.15.6' # The Go version to download (if necessary) and use.
      - uses: secrethub/actions/env-export@v0.2.1
        env:
          LOTUS_RPC_URL: ${{ secrets.LOTUS_RPC_URL }}
      - run: git submodule update --init --recursive
      - run: sudo apt update && sudo apt install -yy build-essential bzr jq pkg-config mesa-opencl-icd ocl-icd-opencl-dev hwloc libhwloc-dev
      - run: make build_CI
      - run: ./rosetta-filecoin-proxy&
      - run: ./rosetta_cli_test_PR.sh
        working-directory: ./rosetta/tests        

